import turtle
turtle.setup(1200,800)
turtle.penup()
turtle.goto(-400,300)
turtle.left(90)
turtle.pendown()
turtle.pensize(2)
turtle.fillcolor("grey")
turtle.begin_fill()
turtle.color("black")
turtle.circle(5,180)
turtle.fd(600)
turtle.circle(5,180)
turtle.fd(600)
turtle.end_fill()
turtle.right(45)
turtle.color("red")
turtle.fillcolor("red")
turtle.begin_fill()
for i in range(4):
    turtle.circle(-40,90)
    turtle.circle(40,90)
turtle.right(135)
turtle.fd(300)
turtle.right(45)
for i in range(4):
    turtle.circle(-40,90)
    turtle.circle(40,90)
turtle.right(135)
turtle.fd(300)
turtle.end_fill()
turtle.penup()
turtle.goto(-370,256)
turtle.right(90)
turtle.pendown()
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.pencolor("yellow")
for i in range(5):
    turtle.fd(60)
    turtle.right(144)
turtle.end_fill()
turtle.penup()
turtle.goto(-277,287)
turtle.right(90)
turtle.pendown()
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.pencolor("yellow")
for i in range(5):
    turtle.fd(20)
    turtle.right(144)
turtle.end_fill()
turtle.penup()
turtle.goto(-256,249)
turtle.right(90)
turtle.pendown()
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.pencolor("yellow")
for i in range(5):
    turtle.fd(20)
    turtle.right(144)
turtle.end_fill()
turtle.penup()
turtle.goto(-268,217)
turtle.right(90)
turtle.pendown()
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.pencolor("yellow")
for i in range(5):
    turtle.fd(20)
    turtle.right(144)
turtle.end_fill()
turtle.penup()
turtle.goto(-295,210)
turtle.right(90)
turtle.pendown()
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.pencolor("yellow")
for i in range(5):
    turtle.fd(20)
    turtle.right(144)
turtle.end_fill()
turtle.done()